### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by lin-snow** [laomaiorg/laomaiorg#1]
博主是否考虑加入photoswipe,可以是文章内的多张图片有一个好的排版和灯箱效果。这是项目地址：https://github.com/dimsemenov/PhotoSwipe

**Comment by laomaiorg** [comment]
> 博主是否考虑加入photoswipe,可以是文章内的多张图片有一个好的排版和灯箱效果。这是项目地址：https://github.com/dimsemenov/PhotoSwipe

不好意思，现在才看到这个问题，我都没有想到会有这个提问，因此平时都不怎么去看这里。
你说的这个请求可以实现，也很简单，以前我就是用这个灯箱的，但是后来用了更加轻量的灯箱来代替。你也可以考虑一下，viewimage。
主题上有这个JS文件，但我并没有集成到主题上，主要是我个人并不需要这个功能。
